package gest;


import com.mongodb.BasicDBObject;

import java.awt.Color;

import java.awt.Point;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import java.util.regex.*;
import com.mongodb.client.*;
import javax.swing.table.*;
import org.bson.Document;
import org.bson.types.ObjectId;


public final class home extends javax.swing.JFrame {
   
   
    public home() {
        initComponents();
        //this.setIconImage(new ImageIcon(getClass().getResource("mini logo.png")).getImage());
         
        //cacher btn  modifier
        
            
        if (login.user_type.equals("user")) {
            btnmodifier.setBackground(new Color(60,60,60));
            btnajouter.setBackground(new Color(60,60,60));
        }
        
        
        /*if (login.user_type.equals("user")) {
            btnmodifier.setBackground(new Color(60,60,60));
            btnajouter.setBackground(new Color(60,60,60));
        }
        else if (login.user_type.equals("admin")) {
            btnmodifier.setBackground(new Color(204,0,51));
            btnajouter.setBackground(new Color(204,0,51));
        }*/
        BasicDBObject query = new BasicDBObject("vendu",false); // hadi hiya la requete  
        FindIterable<org.bson.Document> products = Main.db.getCollection("produit").find(query); //{"vendu":true} // hada howa rak tarsal la requete le mongo 
        fillTable(products);
        
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cpanel = new javax.swing.JPanel();
        Spanelmodifier = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sidepanel = new javax.swing.JPanel();
        btnajouter = new javax.swing.JPanel();
        iditlabelicon = new javax.swing.JLabel();
        btnmodifier = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnsupprimer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnuser = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ipanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnafficher = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        titelpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setLocation(new java.awt.Point(220, 150));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(253, 206, 206)));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-effacer-25.png"))); // NOI18N
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-down-25.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("yassine youcefi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
        );

        cpanel.setBackground(new java.awt.Color(254, 254, 254));

        Spanelmodifier.setMaximumSize(new java.awt.Dimension(452, 402));
        Spanelmodifier.setMinimumSize(new java.awt.Dimension(452, 402));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(254, 254, 254));
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"5ab545363deb298a91807476", "iphone5",  new Integer(1),  new Float(40000.0),  new Integer(2), "appel", "5", "5ac0f7ab0632416701c90714"},
                {"5ab545563deb298a9180747c", "iphone6",  new Integer(1),  new Float(50000.0),  new Integer(3), "appel", "6", "5ac0f7ab0632416701c90714"},
                {"5ab545ab3deb298a91807482", "galaxy s6",  new Integer(1),  new Float(45000.0),  new Integer(2), "samsung", "6", "5ac0f7ab0632416701c90714"},
                {"5ab545cf3deb298a91807488", "galaxy s7",  new Integer(1),  new Float(55000.0),  new Integer(1), "samsung", "7", "5acf7ede124f40e2e4de7f1c"}
            },
            new String [] {
                "Id", "Nom", "Numéro", "Prix", "Quantité", "Marque", "Model", " fournisseure"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(204, 0, 51));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        Spanelmodifier.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
        }

        javax.swing.GroupLayout cpanelLayout = new javax.swing.GroupLayout(cpanel);
        cpanel.setLayout(cpanelLayout);
        cpanelLayout.setHorizontalGroup(
            cpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cpanelLayout.createSequentialGroup()
                .addComponent(Spanelmodifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        cpanelLayout.setVerticalGroup(
            cpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Spanelmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        sidepanel.setBackground(new java.awt.Color(255, 255, 255));

        btnajouter.setBackground(new java.awt.Color(204, 0, 51));
        btnajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajouterMouseClicked(evt);
            }
        });

        iditlabelicon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        iditlabelicon.setForeground(new java.awt.Color(255, 255, 255));
        iditlabelicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-plus-32.png"))); // NOI18N
        iditlabelicon.setText("   Ajouter un produit");

        javax.swing.GroupLayout btnajouterLayout = new javax.swing.GroupLayout(btnajouter);
        btnajouter.setLayout(btnajouterLayout);
        btnajouterLayout.setHorizontalGroup(
            btnajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnajouterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iditlabelicon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnajouterLayout.setVerticalGroup(
            btnajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iditlabelicon, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        btnmodifier.setBackground(new java.awt.Color(204, 0, 51));
        btnmodifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmodifierMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnmodifierMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-modifier-la-propriété-26.png"))); // NOI18N
        jLabel1.setText(" Modifier un produit");

        javax.swing.GroupLayout btnmodifierLayout = new javax.swing.GroupLayout(btnmodifier);
        btnmodifier.setLayout(btnmodifierLayout);
        btnmodifierLayout.setHorizontalGroup(
            btnmodifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnmodifierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnmodifierLayout.setVerticalGroup(
            btnmodifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnsupprimer.setBackground(new java.awt.Color(204, 0, 51));
        btnsupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsupprimerMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-annuler-32.png"))); // NOI18N
        jLabel2.setText("Supprimer produit");

        javax.swing.GroupLayout btnsupprimerLayout = new javax.swing.GroupLayout(btnsupprimer);
        btnsupprimer.setLayout(btnsupprimerLayout);
        btnsupprimerLayout.setHorizontalGroup(
            btnsupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnsupprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnsupprimerLayout.setVerticalGroup(
            btnsupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btnuser.setBackground(new java.awt.Color(204, 0, 51));
        btnuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnuserMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-sortie-32.png"))); // NOI18N
        jLabel3.setText("   Sortie");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnuserLayout = new javax.swing.GroupLayout(btnuser);
        btnuser.setLayout(btnuserLayout);
        btnuserLayout.setHorizontalGroup(
            btnuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnuserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnuserLayout.setVerticalGroup(
            btnuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        ipanel.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/gg_stock.png"))); // NOI18N

        javax.swing.GroupLayout ipanelLayout = new javax.swing.GroupLayout(ipanel);
        ipanel.setLayout(ipanelLayout);
        ipanelLayout.setHorizontalGroup(
            ipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ipanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ipanelLayout.setVerticalGroup(
            ipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ipanelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel12.setForeground(new java.awt.Color(204, 0, 51));
        jLabel12.setText("____________________________________");

        btnafficher.setBackground(new java.awt.Color(204, 0, 51));
        btnafficher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnafficherMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnafficherMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-télévision-25.png"))); // NOI18N
        jLabel14.setText("     Afficher stock");

        javax.swing.GroupLayout btnafficherLayout = new javax.swing.GroupLayout(btnafficher);
        btnafficher.setLayout(btnafficherLayout);
        btnafficherLayout.setHorizontalGroup(
            btnafficherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnafficherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnafficherLayout.setVerticalGroup(
            btnafficherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ipanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnafficher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(btnajouter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addComponent(ipanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnafficher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        titelpanel.setBackground(new java.awt.Color(204, 0, 51));
        titelpanel.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                titelpanelInputMethodTextChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-utilisateur-50.png"))); // NOI18N
        jLabel7.setText("Bienvenue dans votre stock " + (String)login.logged_in_user.get("nom_user") + " " + (String)login.logged_in_user.get("prenom_user"));

        jPanel3.setBackground(new java.awt.Color(204, 0, 51));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTextField1.setSelectionColor(new java.awt.Color(204, 0, 51));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("avec nom : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTextField2.setSelectionColor(new java.awt.Color(204, 0, 51));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("avec marque :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout titelpanelLayout = new javax.swing.GroupLayout(titelpanel);
        titelpanel.setLayout(titelpanelLayout);
        titelpanelLayout.setHorizontalGroup(
            titelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titelpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(titelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titelpanelLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        titelpanelLayout.setVerticalGroup(
            titelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titelpanelLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(titelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(titelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titelpanelLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/mini logo.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("W stock");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(titelpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(titelpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked
    
    private Point initialClick;
    private JFrame parent;
    
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        parent = login.home_interface;
        System.out.println(parent);
        initialClick = evt.getPoint();
        getComponentAt(initialClick);
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        // get location of Window
        int thisX = parent.getLocation().x;
        int thisY = parent.getLocation().y;


        // Determine how much the mouse moved since the initial click
        int xMoved = (thisX + evt.getX()) - (thisX + initialClick.x);
        int yMoved = (thisY + evt.getY()) - (thisY + initialClick.y);

        // Move window to this position
        int X = thisX + xMoved;
        int Y = thisY + yMoved;
        parent.setLocation(X, Y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setBackground(Color.red);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
         jLabel6.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jLabel6MouseExited

    private void titelpanelInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_titelpanelInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_titelpanelInputMethodTextChanged

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String search_value = jTextField1.getText();
        /*if (search_value.equals("")) {
            BasicDBObject query = new BasicDBObject("vendu",false); // hadi hiya la requete  
        FindIterable<org.bson.Document> products = Main.db.getCollection("produit").find(query); //{"vendu":true} // hada howa rak tarsal la requete le mongo 
        fillTable(products);
        }
        else { // request de recherche
            //System.out.println(jTextField1.getText());
            
            BasicDBObject query = new BasicDBObject("nom_produit",jTextField1.getText()); 
           FindIterable<org.bson.Document> products = Main.db.getCollection("produit").find(query); 
            fillTable(products);
            
        }*/
        BasicDBObject query = new BasicDBObject();
        query.put("vendu",false); // hadi hiya la requete  
        //if (!search_value.equals("")) // requete de tous les produit si la bar de recherche est vide
            //query.append("nom_produit",  "" new BasicDBObject("$regex",".+" search_value "+."));
        FindIterable<org.bson.Document> products;
        Pattern regex = Pattern.compile(".*" + search_value + ".*", Pattern.CASE_INSENSITIVE);
        if (!search_value.equals(""))    
            query.append("nom_produit",regex);
 
            products = Main.db.getCollection("produit").find(query);
        fillTable(products);
              
    }//GEN-LAST:event_jTextField1KeyReleased

    private void btnuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuserMousePressed
        // TODO add your handling code here:
        /*setColor(tnuser);
        resetColor(btnajouter);
        resetColor(btnsupprimer);
        resetColor(btnmodifier);*/
    }//GEN-LAST:event_btnuserMousePressed

    private void logout(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout
        // TODO add your handling code here:

    }//GEN-LAST:event_logout

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:

        login.home_interface.setVisible(false);
        Main.login_interface.setVisible(true);
    }//GEN-LAST:event_jLabel3MousePressed
    
    private void btnmodifierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodifierMousePressed
      
    }//GEN-LAST:event_btnmodifierMousePressed
    public static int selectedrowindex;
    public static String clicked_id = null;
    public static String nom_prod = null ; 
    public static String numero = null ; 
    public static String prix = null ; 
    public static String marque = null ;
    public static  String modele = null;
    public static String quantite = null ;
    private void btnmodifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodifierMouseClicked
        // TODO add your handling code here:
            // TODO add your handling code here:
    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    
    clicked_id = model.getValueAt(selectedrowindex,0).toString();
    nom_prod = model.getValueAt(selectedrowindex,1).toString();
    numero = model.getValueAt(selectedrowindex,2).toString();
    prix= model.getValueAt(selectedrowindex,3).toString();
    quantite = model.getValueAt(selectedrowindex,4).toString();
    marque = model.getValueAt(selectedrowindex,5).toString();
    modele = model.getValueAt(selectedrowindex,6).toString();

    MongoCollection<Document> collection = Main.db.getCollection("produit");  
    Document fond = (Document) collection.find(new Document("_id",new ObjectId(clicked_id))).first(); 
    org.bson.Document stock = new org.bson.Document("quantite",Integer.valueOf(quantite));
    if (fond != null){
        System.out.println("/////////////////////");
        System.out.println(nom_prod + " yes mate");
        String aa = nom_prod;
        String ab = numero;
        String ac = prix;
        String ad = marque;
        String ae = modele;
        String af = quantite;
        org.bson.Document updatevalue1 = new Document("nom_produit",aa)
                .append("numero_produit",ab)
                .append("prix",ac)
                .append("marque",ad)
                .append("modele",ae)
                .append("id_stock",stock);
        Main.db.getCollection("stock").insertOne(stock);
        org.bson.Document updateoperation1 = new Document("$set", updatevalue1);
        collection.updateOne(fond, updateoperation1);
    
    } 
    

    //mis a jours la table    
       BasicDBObject query = new BasicDBObject("vendu",false); 
       FindIterable<org.bson.Document> products_new = Main.db.getCollection("produit").find(query); //{"vendu":true} // hada howa rak tarsal la requete le mongo 
       login.home_interface.fillTable(products_new);    
        
       
    }//GEN-LAST:event_btnmodifierMouseClicked

    private void btnajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajouterMouseClicked
        // TODO add your handling code here:
        //removingpanel
        if (login.user_type.equals("admin")) {
            //pour le panel d'affichage
            cpanel.removeAll();
            cpanel.repaint();
            cpanel.revalidate();

            //addingpanel
            cpanel.add(new Ajouter().getContentPane());
            cpanel.repaint();
            cpanel.revalidate();
            
            sidepanel.remove(btnmodifier);
            sidepanel.remove(btnsupprimer);
            sidepanel.repaint();
            sidepanel.revalidate();
            

            //pour le panel de filtrage
            titelpanel.remove(jPanel3);
            titelpanel.repaint();
            titelpanel.revalidate();
            
            titelpanel.remove(jPanel4);
            titelpanel.repaint();
            titelpanel.revalidate();

            
            
        }

    }//GEN-LAST:event_btnajouterMouseClicked

    private void btnafficherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnafficherMouseClicked
        // TODO add your handling code here:
         //removing panel
            cpanel.removeAll();
            cpanel.repaint();
            cpanel.revalidate();

        //addingpanel
            cpanel.add(Spanelmodifier);
            cpanel.repaint();
            cpanel.revalidate();
        
        
         //add buttons
            sidepanel.add(btnmodifier);
            sidepanel.add(btnsupprimer);
            sidepanel.repaint();
            sidepanel.revalidate();
         //add recherche
            titelpanel.add(jPanel4);
            titelpanel.repaint();
            titelpanel.revalidate();
           
            titelpanel.add(jPanel3);
            titelpanel.repaint();
            titelpanel.revalidate();
            
    }//GEN-LAST:event_btnafficherMouseClicked

    private void btnafficherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnafficherMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnafficherMousePressed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        jLabel8.setBackground(Color.red);
    }//GEN-LAST:event_jLabel8MouseEntered
    
   
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    
    selectedrowindex = jTable1.getSelectedRow();
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnsupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsupprimerMouseClicked
        // TODO add your handling code here:
    //afficher panel de recherche

        titelpanel.add(jPanel3);
        titelpanel.repaint();
        titelpanel.revalidate();
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        clicked_id = model.getValueAt(selectedrowindex,0).toString();
        MongoCollection<Document> collection = Main.db.getCollection("produit");
        collection.deleteOne(new Document("_id", new ObjectId(clicked_id)));
        
    //mis a jours la table    
       BasicDBObject query = new BasicDBObject("vendu",false); 
       FindIterable<org.bson.Document> products_new = Main.db.getCollection("produit").find(query); //{"vendu":true} // hada howa rak tarsal la requete le mongo 
       login.home_interface.fillTable(products_new);    
    }//GEN-LAST:event_btnsupprimerMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        String search_value = jTextField2.getText();
        BasicDBObject query = new BasicDBObject();
        query.put("vendu",false); // hadi hiya la requete  
        //if (!search_value.equals("")) // requete de tous les produit si la bar de recherche est vide
            //query.append("nom_produit",  "" new BasicDBObject("$regex",".+" search_value "+."));
        FindIterable<org.bson.Document> products;
        Pattern regex = Pattern.compile(".*" + search_value + ".*", Pattern.CASE_INSENSITIVE);
        if (!search_value.equals(""))    
            query.append("marque",regex);
 
            products = Main.db.getCollection("produit").find(query);
        fillTable(products);
    }//GEN-LAST:event_jTextField2KeyReleased

    

    void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(255,51,51));
        
    }
   
    void resetColor(JPanel panel){
     
        panel.setBackground(new java.awt.Color( 204,0,51));  
    
    }

    public JPanel getCpanel() {
        return cpanel;
    }
    
    
    public JScrollPane getSpanelmodifier() {
        return Spanelmodifier;
    }
    
    public JPanel getBtnAjouter() {
        return btnajouter;
    }
    
    public JPanel getsidepanel(){
        return  sidepanel;
    }
    public JPanel getbtnsupprimer(){
        return  btnsupprimer;
    }
    public JPanel getbtnmodifier(){
        return  btnmodifier;
    }
    
    public JPanel getJpanel3(){
        return jPanel3;
    }
    public JPanel getjPanel4() {
        return jPanel4;
    }
    public  JPanel gettp(){
        return titelpanel;
    }
    public JPanel getjPanel2(){
        return jPanel2;  
    }
    
    public void fillTable(FindIterable<org.bson.Document>  products) {
        Object[] cols = {"Id","Nom","Numéro","Prix","Quantité","Marque","Model","fornisseur"};
        int nb_products = 0;
        for (org.bson.Document product : products){
            nb_products ++;
        }
        Object[][] content = new Object[nb_products][8];
        int i = 0;
        for (org.bson.Document product : products){
            content[i][0] = product.get("_id").toString();
            content[i][1] = product.get("nom_produit").toString();
            content[i][2] = product.get("numero_produit").toString();
            content[i][3] = product.get("prix").toString();
            content[i][4] = ((org.bson.Document)product.get("id_stock")).get("quantite");
            content[i][5] = product.get("marque").toString();
            content[i][6] = product.get("modele").toString();
            content[i][7] = ((org.bson.Document)product.get("id_fournisseur")).get("nom_prenom_fournisseur");
            i++;
        }
        DefaultTableModel tbm = new DefaultTableModel(content,cols);
        this.jTable1.setModel(tbm);
       
        //String s = (String)tbm.getDataVector().elementAt(jTable1.getSelectedRow());
       // System.out.println(s);
        

        /*TableModel myModel = jTable1.getModel();
        for (i = 0; i < content.length; i++) {
            for (int j = 0; j < content[i].length; j++) {
                myModel.setValueAt(content[i][j], i, j);
            }
        }*/

    }
    

    
    
//    public static void main(String args[]) {
//       
//        java.awt.EventQueue.invokeLater(() -> {
//            new home().setVisible(true);
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Spanelmodifier;
    private javax.swing.JPanel btnafficher;
    private javax.swing.JPanel btnajouter;
    private javax.swing.JPanel btnmodifier;
    private javax.swing.JPanel btnsupprimer;
    private javax.swing.JPanel btnuser;
    private javax.swing.JPanel cpanel;
    private javax.swing.JLabel iditlabelicon;
    private javax.swing.JPanel ipanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel titelpanel;
    // End of variables declaration//GEN-END:variables
}
